import type {Book,Character,Relation} from './reader-model';
const c=(id:string,name:string,description:string,aliases:string[]=[],afterSection=0):Character=>({id,name,description,aliases:[name,...aliases],afterSection,evidence:'Eigene Lesehilfe zum Originaltext; noch nicht fachredaktionell geprüft.'});
const rel=(active:string,passive:string,description:string,afterSection=0):Relation=>({active,passive,mutual:[],type:'literary',description,afterSection});
const introductions:Record<string,string>={
 iphigenie:'Iphigenie lebt fern ihrer Heimat als Priesterin auf Tauris. Gleich zu Beginn wird ihre Sehnsucht nach Griechenland hörbar.',
 krug:'Ein Gerichtstag beginnt mit einem Rätsel: Dorfrichter Adam ist verletzt. Sein Schreiber Licht möchte wissen, was geschehen ist.',
 faust:'Ein Gelehrter sucht nach Erkenntnis, die ihm seine Bücher nicht geben. Zueignung, Vorspiel und Prolog eröffnen das Drama aus verschiedenen Perspektiven.',
 woyzeck:'Büchners Drama blieb ein Fragment. Hier liest du die getrennten Handschriftengruppen H1–H4. Die Reihenfolge in deinem Schulbuch kann anders sein.',
 nathan:'Im Jerusalem der Kreuzzüge begegnen sich Menschen verschiedener Religionen. Lessing stellt die Frage, woran sich Menschlichkeit zeigt.',
 emilia:'Ein Prinz, ein Bild und ein Arbeitstag am Hof: Schon zu Beginn treffen private Wünsche auf politische Macht.',
 kabale:'Die Liebe zwischen Luise Miller und Ferdinand von Walter gerät in Konflikt mit Familie, Stand und höfischer Macht.',
 maria:'Maria Stuart ist in England gefangen. Schillers Drama macht den Konflikt zwischen persönlichem Schicksal und politischem Handeln sichtbar.',
 verwandlung:'Gregor Samsa wacht verwandelt auf. Trotzdem kreisen seine ersten Gedanken um Arbeit, Pflichten und die Erwartungen seiner Familie.'
};
const people:Record<string,Character[]>={
 iphigenie:[c('iphigenie','Iphigenie','Griechin und Priesterin der Diana auf Tauris. Sie sehnt sich nach ihrer Heimat und fühlt sich trotz ihrer Rettung unfrei.',['Priesterin']),c('thoas','Thoas','König der Taurier. Iphigenie bezeichnet ihn zu Beginn als edlen Mann, erlebt ihren Aufenthalt aber als Bindung.'),c('arkas','Arkas','Bote und Vertrauter des Königs Thoas. Er spricht mit Iphigenie über ihre Stellung auf Tauris.'),c('orest','Orest','Ein Grieche, der mit Pylades nach Tauris kommt. Seine Vorgeschichte prägt sein Handeln.',[],3),c('pylades','Pylades','Orests Freund und Begleiter. Er wägt Möglichkeiten ab und sucht nach einem Ausweg.',[],3),c('diana','Diana','Göttin, deren Tempel Iphigenie auf Tauris dient. In der griechischen Mythologie entspricht ihr Artemis.',['Dianens']),c('agamemnon','Agamemnon','Griechischer Heerführer vor Troja und Iphigenies Vater. Iphigenie erinnert an ihn in ihrem ersten Monolog.'),c('elektra','Elektra','Iphigenies Schwester; im ersten Monolog als Teil ihrer Familie genannt.',['Elektren'])],
 krug:[c('adam','Adam','Dorfrichter in Huisum. Er erscheint am Anfang verletzt und erklärt Licht, er sei gestürzt.'),c('licht','Licht','Gerichtsschreiber. Er bemerkt Adams Verletzungen und fragt hartnäckig nach.'),c('walter','Walter','Gerichtsrat, der das Dorfgericht kontrolliert.'),c('eve','Eve','Marthe Rulls Tochter. Ihre Aussagen werden für die Verhandlung wichtig.'),c('frau_marthe','Frau Marthe','Klägerin vor dem Dorfgericht. Sie verlangt Aufklärung über ihren zerbrochenen Krug.',['Marthe','Marthe Rull']),c('ruprecht','Ruprecht','Eves Verlobter. Er wird mit dem zerbrochenen Krug in Verbindung gebracht.')],
 verwandlung:[c('gregor','Gregor Samsa','Reisender und Sohn der Familie Samsa. Er erwacht zu Beginn verwandelt und sorgt sich sofort um seine Arbeit.',['Gregor','Gregors']),c('grete','Grete Samsa','Gregors Schwester. Wie sie auf ihn reagiert, lässt sich im Verlauf der Erzählung beobachten.',['Grete','Gretes']),c('vater','Herr Samsa','Gregors Vater. Die Familie hängt zu Beginn finanziell von Gregors Arbeit ab.',['Vater']),c('mutter','Frau Samsa','Gregors Mutter. Sie versucht zunächst, ihn hinter seiner verschlossenen Zimmertür zu erreichen.',['Mutter']),c('prokurist','Prokurist','Vertreter von Gregors Arbeitgeber. Sein Besuch bringt den Druck der Arbeitswelt in die Wohnung.',['Prokuristen'])],
 faust:[c('faust','Faust','Gelehrter, der an den Grenzen seines Wissens leidet. Er sucht unmittelbare Erfahrung und ein umfassenderes Verständnis der Welt.'),c('mephistopheles','Mephistopheles','Eine teuflische Figur, die im Prolog mit dem Herrn über Faust spricht.',['Mephisto']),c('margarete','Margarete','Eine junge Frau, der Faust begegnet. Häufig wird sie Gretchen genannt.',['Gretchen','Gretchens'],9),c('wagner','Wagner','Fausts gelehrter Gesprächspartner. Sein Verständnis von Wissen unterscheidet sich von Fausts Suche.')]
};
const relationships:Record<string,Relation[]>={
 iphigenie:[rel('iphigenie','thoas','Thoas ist der König des Landes, in dem Iphigenie lebt. Sie steht unter seinem Schutz, empfindet ihre Bindung an Tauris aber als Einschränkung. Beleg: Erster Auftritt, V. 33–34.'),rel('iphigenie','diana','Iphigenie dient Diana als Priesterin. Sie empfindet Dankbarkeit für ihre Rettung und zugleich Widerwillen gegen das Leben in der Fremde. Beleg: V. 35–42.'),rel('iphigenie','agamemnon','Agamemnon ist Iphigenies Vater. Sie erinnert an die Opferung in Aulis. Beleg: V. 41–46.'),rel('orest','pylades','Pylades begleitet Orest als Freund. In den gemeinsamen Gesprächen zeigt sich sein pragmatisches Handeln.',3),rel('iphigenie','orest','Iphigenie und Orest sind Geschwister. Ihre Wiedererkennung ist für den dritten Aufzug entscheidend.',8),rel('arkas','thoas','Arkas handelt als Bote und Vertrauter des Königs. Beleg: Zweiter Auftritt, V. 54 ff.',1)],
 krug:[rel('adam','licht','Adam ist der Dorfrichter, Licht sein Schreiber. Zu Beginn fragt Licht nach Adams Verletzungen; Adams Erklärungen wecken neue Fragen.'),rel('adam','walter','Walter kontrolliert als Gerichtsrat die Amtsführung des Dorfrichters Adam.'),rel('eve','ruprecht','Eve und Ruprecht sind verlobt. Misstrauen belastet ihre Beziehung.'),rel('eve','frau_marthe','Eve ist die Tochter der Klägerin Marthe Rull.')],
 verwandlung:[rel('gregor','grete','Gregor und Grete sind Geschwister. Ihre Beziehung verändert sich unter dem Druck von Gregors Verwandlung.'),rel('gregor','vater','Vater und Sohn leben im selben Haushalt. Gregors Arbeit sichert zu Beginn den Lebensunterhalt der Familie.'),rel('gregor','mutter','Frau Samsa ist Gregors Mutter. Ihr erster Kontakt mit ihm geschieht durch die verschlossene Tür.'),rel('gregor','prokurist','Der Prokurist vertritt Gregors Arbeitgeber und verlangt eine Erklärung für sein Fernbleiben.')],
 faust:[rel('faust','wagner','Beide beschäftigen sich mit Wissen, setzen aber andere Schwerpunkte. Fausts Unzufriedenheit trifft auf Wagners Vertrauen in gelehrte Arbeit.',3),rel('faust','mephistopheles','Mephistopheles stellt Fausts Suche nach Erkenntnis auf die Probe. Ihre Vereinbarung wird im Studierzimmer ausgehandelt.',6)]
};
export function enrichBook(book:Book):Book {
 const overrides=people[book.id]??[];
 const chars=book.characters.map(p=>overrides.find(o=>o.id===p.id||o.name.toLowerCase()===p.name.toLowerCase())??p);
 for(const p of overrides) if(!chars.some(c=>c.id===p.id))chars.push(p);
 return {...book,referenceMode:book.id==='woyzeck'?'paragraph':book.referenceMode,characters:chars,relations:[...(relationships[book.id]??[]),...book.relations],introduction:introductions[book.id]};
}

