import Link from 'next/link';
export const metadata={title:'Datenschutz · Buchtutor'};
export default function Privacy(){
 const complete=!!(process.env.OPERATOR_NAME&&process.env.OPERATOR_ADDRESS&&process.env.OPERATOR_EMAIL);
 return <main className="legal-page"><Link href="/?view=library">← Zur Bibliothek</Link><h1>Datenschutz</h1>
 {!complete&&<p className="placeholder-notice">Entwurfsstand vom 25. September 2026. Betreiber und Kontakt werden noch ergänzt. Die folgenden Hinweise beschreiben die technische Umsetzung dieser Vercel-Version.</p>}
 <p>Verantwortlich ist der im <Link href="/impressum">Impressum</Link> genannte Betreiber.</p>
 <h2>Deine Lesedaten</h2><p>Lesestand, Einstellungen, Markierungen, Notizen und ausdrücklich gespeicherte Analysen liegen im Browser auf deinem Gerät. Diese Daten werden nicht an unseren Server übertragen. Es gibt keine Schülerkonten oder Werbung.</p>
 <p>Unter Einstellungen → Geräteübertragung kannst du eine komprimierte, mit einem selbst gewählten Passwort verschlüsselte Sicherung erstellen oder einlesen. Beide Schritte laufen auf deinem Gerät. Die Sicherung ist eine manuelle Übertragung. Der Markdown-Export im Notizbuch ist eine lesbare, unverschlüsselte Datei. Browserdaten bleiben gespeichert, bis du sie löschst; ohne Sicherung können sie verloren gehen.</p>
 <h2>Hosting</h2><p>Die Website wird von Vercel bereitgestellt. Beim Aufruf werden insbesondere IP-Adresse, Zeitpunkt, angefragte Adresse und technische Browserinformationen für die Auslieferung und die Absicherung des Dienstes verarbeitet. Technische Betriebsprotokolle können beim Hosting-Anbieter entstehen; die Anwendung schreibt keine Fragen, Notizen oder KI-Antworten in ihre Protokolle. Vercel kann Daten auch außerhalb der EU verarbeiten. Weitere Angaben stehen in den <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noreferrer">Datenschutzhinweisen von Vercel</a>.</p>
 <h2>KI-Lesehilfen</h2><p>Erst wenn du eine Analyse anforderst, wird geprüft, ob bereits eine vorbereitete oder gemeinsam gespeicherte Antwort vorliegt. Für eine neue Antwort werden die ausgewählte öffentliche Textstelle, begrenzter Umgebungstext, Angaben zum Werk und bei einer eigenen Frage deren Wortlaut über OpenRouter an einen geeigneten Modellanbieter übertragen. Private Notizen oder deine übrigen Lesedaten werden nicht mitgeschickt. Schreibe keine Namen oder persönlichen Angaben in eigene Fragen.</p>
 <p>Vorgesehen ist OpenAI GPT-6 Luna mit maximalem Reasoning. Die Verbindung fordert Anbieter ohne dauerhafte Speicherung von Anfrage- und Antwortinhalten (ZDR) und ohne Datensammlung an. Das verhindert die notwendige Verarbeitung und technische Abrechnungsmetadaten nicht. Eine Verarbeitung ausschließlich in der EU ist damit nicht zugesichert. Informationen dazu: <a href="https://openrouter.ai/privacy" target="_blank" rel="noreferrer">OpenRouter-Datenschutz</a>. Ohne eingerichteten Betreiber-Schlüssel werden keine neuen KI-Antworten erzeugt.</p>
 <h2>Gemeinsame Antworten und Anfragegrenzen</h2><p>Standardanalysen öffentlicher Werktexte werden ohne Gerätekennung in Upstash Redis in Frankfurt gespeichert, höchstens 90 Tage und insgesamt bis zu 3.000 Einträge. Eigene Fragen und die dazugehörigen Antworten werden dort nicht gespeichert. Eine Antwort zu einer eigenen Frage kannst du ausdrücklich auf deinem Gerät sichern.</p>
 <p>Zum Begrenzen neuer Modellaufrufe entsteht eine zufällige Kennung im lokalen Browser-Speicher. Der Server bildet daraus einen täglich wechselnden kryptografischen Wert und zählt neue Anfragen. Zähler verfallen spätestens kurz nach dem nächsten UTC-Tageswechsel; kurzfristige Lastzähler nach zwei Minuten. Die Standardgrenze liegt bei 50 neuen Anfragen pro Gerät und Tag, zusätzlich gilt ein Gesamtlimit. Vorhandene Antworten zählen nicht mit. Ohne Anmeldung ist das kein strenges Limit pro Person. Weitere Anbieterinformationen: <a href="https://upstash.com/trust/privacy.pdf" target="_blank" rel="noreferrer">Upstash-Datenschutz</a>.</p>
 <h2>Besucherstatistik</h2><p>Auf den öffentlichen Seiten verwenden wir Vercel Web Analytics, um Aufrufe und die Nutzung nach Gerät, Browser und ungefährer Herkunft zu verstehen. Vercel verarbeitet dafür technische Verbindungsdaten und die verweisende Website. Laut Anbieter werden keine Analytics-Cookies eingesetzt; der zur Besuchszählung verwendete Hash wird nach 24 Stunden verworfen. Zusammengefasste Statistiken bleiben im Vercel-Dashboard verfügbar.</p>
 <p>Unsere Einbindung übermittelt nur den Seitenpfad, ohne URL-Parameter oder Sprungmarken. Werk, Vers, Leseposition, Fragen und Notizen werden nicht als Statistikereignisse gesendet. Die Betreiberverwaltung ist ausgenommen. Wenn dein Browser „Do Not Track“ oder „Global Privacy Control“ signalisiert, laden wir das Statistikskript nicht. Weitere Informationen: <a href="https://vercel.com/docs/analytics/privacy-policy" target="_blank" rel="noreferrer">Datenschutz bei Vercel Web Analytics</a>.</p>
 <h2>KI-Verbrauch und Betreiberzugang</h2><p>Für Kostenkontrolle und Betriebssicherheit speichern wir in Upstash ausschließlich Tageszähler: neue Modellaufrufe, vorhandene Antworten, Fehler, Begrenzungen, Tokenmengen und vom KI-Anbieter gemeldete Kosten. Diese Zahlen enthalten keine Fragen, Antworttexte, Notizen, IP-Adressen oder Gerätekennungen und werden nach 90 Tagen gelöscht. Kurzlebige zufällige Transaktionskennungen verhindern für zehn Minuten eine doppelte Zählung bei einer technischen Wiederholung; sie sind keinem Besucher zugeordnet.</p>
 <p>Die geschützte Statistikverwaltung setzt nach Anmeldung des Betreibers ein technisch notwendiges Sitzungscookie für acht Stunden. Dieses Cookie wird für Schüler beim Lesen nicht gesetzt. Fehlgeschlagene Betreiberanmeldungen werden ohne Personenkennung für höchstens eine Minute gezählt.</p>
 <h2>Zwecke, Rechtsgrundlage und Rechte</h2><p>Die Verarbeitung dient den ausdrücklich aufgerufenen Lese- und Analysefunktionen, dem sicheren Betrieb sowie der zusammengefassten Reichweiten- und Kostenkontrolle. Soweit keine andere Rechtsgrundlage greift, stützen wir diese Zwecke auf das berechtigte Interesse an Betrieb und Verbesserung dieses Bildungsangebots (Art. 6 Abs. 1 Buchst. f DSGVO). Der lokale Speicher dient den von dir gewünschten Funktionen. Die konkrete Einbindung der Dienstleister und internationale Übermittlungen sind vor dem regulären Betrieb durch den Betreiber zu prüfen.</p>
 <p>Du kannst Auskunft, Berichtigung, Löschung oder Einschränkung sowie gegebenenfalls Datenübertragbarkeit verlangen und der Verarbeitung auf Grundlage berechtigter Interessen widersprechen. Wende dich an den Kontakt im Impressum. Du hast außerdem das Recht auf Beschwerde bei einer Datenschutzaufsichtsbehörde. Lokal gespeicherte Notizen sind für den Betreiber nicht einsehbar; du verwaltest sie auf deinem Gerät.</p>
 </main>;
}
